# gcloud builds submit --config=./generic/cloudbuild.yaml . --substitutions=_VERSION=0.8.0
steps:
- name: maven:3.6.2-jdk-8-slim
  entrypoint: 'mvn'
  args: ['clean','package','-f','./pom.xml']
- name: gcr.io/cloud-builders/docker
  args: ['build','-t', 'gcr.io/$PROJECT_ID/vertx-webhook:${_VERSION}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/vertx-webhook:latest', '.']
images: ['gcr.io/$PROJECT_ID/vertx-webhook']
substitutions:
    _VERSION: 0.8.0